server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: "Prod Application"
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: /var/lib/tomcat9/webapps/edumarket/resource/upload
  datasource:
    url: jdbc:mariadb://10.41.1.127:3306/team15
    username: team15
    password: team15
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5  # ?? ?? ?
      maximum-pool-size: 20  # ?? ?? ?
      idle-timeout: 30000  # ?? ??? ?? ?? ?? (ms)
      connection-timeout: 30000  # ?? ?? ?? (ms)
      max-lifetime: 1800000  # ?? ?? ?? (ms)
mybatis:
  type-aliases-package: com.admin.mapper
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework: ERROR
LOG_PATH: /var/lib/tomcat9/edumarket/resource/upload