server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  application:
    name: "Local Application"
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: C:/storage/edumarket
  datasource:
    url: jdbc:mariadb://localhost:3306/edumarket
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 2  # 최소 연결 수
      maximum-pool-size: 10  # 최대 연결 수
      idle-timeout: 30000  # 유휴 연결의 최대 대기 시간 (ms)
      connection-timeout: 30000  # 연결 시간 초과 (ms)
      max-lifetime: 1800000  # 연결 최대 수명 (ms)
mybatis:
  type-aliases-package: com.admin.mapper
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework: DEBUG
LOG_PATH: C:/storage/edumarket